// Copyright 2024 Jay Gowdy
// SPDX-License-Identifier: MIT

//! Git commit-message-source variants and the notes ref
//! namespace, all on a gitenc-configured repo:
//!
//! - `git commit -F -` (message from stdin) produces an
//!   sshenc-signed commit. The signing path doesn't depend on
//!   how the message arrives.
//! - `git commit --fixup HEAD` produces a signed `fixup!`
//!   commit. The autogenerated subject mustn't break signing
//!   and the new HEAD must verify.
//! - `git notes add` writes to `refs/notes/commits` (a
//!   different ref namespace from branches/tags). Adding a
//!   note alongside signed commits doesn't disturb the
//!   commit's signature; the underlying commit still verifies.

#![cfg(unix)]
#![allow(clippy::panic, clippy::unwrap_used, clippy::print_stderr)]

use sshenc_e2e::{docker_skip_reason, run, shared_enclave_pubkey, SshencEnv, SHARED_ENCLAVE_LABEL};
use std::process::Stdio;

fn skip_if_no_docker(test_name: &str) -> bool {
    if let Some(reason) = docker_skip_reason() {
        eprintln!("skip {test_name}: {reason}");
        return true;
    }
    false
}

fn plant_meta_and_pub(env: &SshencEnv, label: &str, name: &str, email: &str, enclave: &str) {
    let dir = env.home().join(".sshenc").join("keys");
    std::fs::create_dir_all(&dir).expect("mkdir gitenc meta dir");
    std::fs::write(
        dir.join(format!("{label}.meta")),
        serde_json::to_string_pretty(&serde_json::json!({
            "app_specific": {
                "git_name": name,
                "git_email": email,
            }
        }))
        .unwrap(),
    )
    .expect("write meta");
    std::fs::create_dir_all(env.ssh_dir()).expect("mkdir ssh dir");
    std::fs::write(
        env.ssh_dir().join(format!("{label}.pub")),
        format!("{enclave}\n"),
    )
    .expect("write pub");
}

fn make_signed_repo(env: &SshencEnv, name: &str, enclave: &str) -> std::path::PathBuf {
    plant_meta_and_pub(
        env,
        SHARED_ENCLAVE_LABEL,
        "msg signer",
        "msg@e2e.test",
        enclave,
    );
    let repo = env.home().join(name);
    std::fs::create_dir_all(&repo).expect("mkdir");
    assert!(env
        .git_cmd()
        .current_dir(&repo)
        .args(["init", "-q", "-b", "main"])
        .status()
        .expect("git init")
        .success());
    let cfg = run(env
        .gitenc_cmd()
        .expect("gitenc cmd")
        .current_dir(&repo)
        .args(["--config", SHARED_ENCLAVE_LABEL]))
    .expect("gitenc --config");
    assert!(cfg.succeeded(), "gitenc --config: {}", cfg.stderr);
    repo
}

fn make_commit(env: &SshencEnv, repo: &std::path::Path, file: &str, content: &str, msg: &str) {
    std::fs::write(repo.join(file), content.as_bytes()).expect("write file");
    let add = run(env.git_cmd().current_dir(repo).args(["add", file])).expect("git add");
    assert!(add.succeeded(), "git add: {}", add.stderr);
    let commit = run(env
        .git_cmd()
        .current_dir(repo)
        .args(["commit", "-q", "-m", msg]))
    .expect("git commit");
    assert!(commit.succeeded(), "git commit: {}", commit.stderr);
}

/// `git commit -F -` reads the message from stdin and produces
/// an sshenc-signed commit just like `-m` does.
#[test]
#[ignore = "requires docker"]
fn commit_with_message_from_stdin_is_signed() {
    if skip_if_no_docker("commit_with_message_from_stdin_is_signed") {
        return;
    }
    let mut env = SshencEnv::new().expect("env");
    let enclave = shared_enclave_pubkey(&env).expect("shared enclave");
    env.start_agent().expect("start agent");
    let repo = make_signed_repo(&env, "stdin-msg-repo", &enclave);

    std::fs::write(repo.join("a.txt"), b"stdin-bodied\n").expect("write");
    let add = run(env.git_cmd().current_dir(&repo).args(["add", "a.txt"])).expect("git add");
    assert!(add.succeeded(), "git add: {}", add.stderr);

    // git commit -F - reads the message from stdin.
    let mut child = env
        .git_cmd()
        .current_dir(&repo)
        .args(["commit", "-q", "-F", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn git commit -F -");
    {
        use std::io::Write;
        let stdin = child.stdin.as_mut().expect("stdin handle");
        stdin
            .write_all(b"stdin-supplied subject\n\nbody from stdin\n")
            .expect("write stdin");
    }
    let out = child.wait_with_output().expect("wait git commit");
    assert!(
        out.status.success(),
        "git commit -F - failed; stderr:\n{}",
        String::from_utf8_lossy(&out.stderr)
    );

    let verify = run(env
        .git_cmd()
        .current_dir(&repo)
        .args(["verify-commit", "HEAD"]))
    .expect("verify-commit");
    assert!(
        verify.succeeded(),
        "verify-commit on stdin-message HEAD failed; stderr:\n{}",
        verify.stderr
    );

    let body = run(env
        .git_cmd()
        .current_dir(&repo)
        .args(["log", "-1", "--format=%s"]))
    .expect("log subject");
    assert!(body.succeeded(), "git log: {}", body.stderr);
    assert_eq!(
        body.stdout.trim(),
        "stdin-supplied subject",
        "subject didn't round-trip from stdin"
    );
}

/// `git commit --fixup HEAD` produces a signed `fixup!` commit.
#[test]
#[ignore = "requires docker"]
fn commit_fixup_produces_signed_fixup_commit() {
    if skip_if_no_docker("commit_fixup_produces_signed_fixup_commit") {
        return;
    }
    let mut env = SshencEnv::new().expect("env");
    let enclave = shared_enclave_pubkey(&env).expect("shared enclave");
    env.start_agent().expect("start agent");
    let repo = make_signed_repo(&env, "fixup-repo", &enclave);

    make_commit(&env, &repo, "a.txt", "first\n", "first commit subject");

    // Stage another change and create a --fixup against HEAD.
    std::fs::write(repo.join("a.txt"), b"first updated\n").expect("write");
    let add = run(env.git_cmd().current_dir(&repo).args(["add", "a.txt"])).expect("git add");
    assert!(add.succeeded(), "git add: {}", add.stderr);

    let fixup = run(env
        .git_cmd()
        .current_dir(&repo)
        .args(["commit", "-q", "--fixup", "HEAD"]))
    .expect("commit --fixup");
    assert!(fixup.succeeded(), "commit --fixup: {}", fixup.stderr);

    // The new HEAD's subject must start with "fixup! ".
    let subject = run(env
        .git_cmd()
        .current_dir(&repo)
        .args(["log", "-1", "--format=%s"]))
    .expect("log subject");
    assert!(subject.succeeded(), "git log: {}", subject.stderr);
    assert!(
        subject.stdout.starts_with("fixup! "),
        "expected fixup! subject; got:\n{}",
        subject.stdout
    );

    let verify = run(env
        .git_cmd()
        .current_dir(&repo)
        .args(["verify-commit", "HEAD"]))
    .expect("verify-commit");
    assert!(
        verify.succeeded(),
        "verify-commit on --fixup HEAD failed; stderr:\n{}",
        verify.stderr
    );
}

/// `git notes add` writes to refs/notes/commits and doesn't
/// disturb the underlying commit's signature.
#[test]
#[ignore = "requires docker"]
fn git_notes_add_does_not_disturb_commit_signature() {
    if skip_if_no_docker("git_notes_add_does_not_disturb_commit_signature") {
        return;
    }
    let mut env = SshencEnv::new().expect("env");
    let enclave = shared_enclave_pubkey(&env).expect("shared enclave");
    env.start_agent().expect("start agent");
    let repo = make_signed_repo(&env, "notes-repo", &enclave);

    make_commit(&env, &repo, "a.txt", "first\n", "first");

    let head_sha = run(env.git_cmd().current_dir(&repo).args(["rev-parse", "HEAD"]))
        .expect("rev-parse")
        .stdout
        .trim()
        .to_string();

    let notes =
        run(env
            .git_cmd()
            .current_dir(&repo)
            .args(["notes", "add", "-m", "annotation", "HEAD"]))
        .expect("git notes add");
    assert!(notes.succeeded(), "git notes add: {}", notes.stderr);

    // The commit sha hasn't changed (notes are out-of-tree).
    let head_after = run(env.git_cmd().current_dir(&repo).args(["rev-parse", "HEAD"]))
        .expect("rev-parse after")
        .stdout
        .trim()
        .to_string();
    assert_eq!(head_sha, head_after, "notes add must not move HEAD");

    // The signature still verifies.
    let verify = run(env
        .git_cmd()
        .current_dir(&repo)
        .args(["verify-commit", "HEAD"]))
    .expect("verify-commit");
    assert!(
        verify.succeeded(),
        "verify-commit after notes add failed; stderr:\n{}",
        verify.stderr
    );

    // And the note is retrievable.
    let show = run(env
        .git_cmd()
        .current_dir(&repo)
        .args(["notes", "show", "HEAD"]))
    .expect("git notes show");
    assert!(show.succeeded(), "git notes show: {}", show.stderr);
    assert!(
        show.stdout.contains("annotation"),
        "expected note text; got:\n{}",
        show.stdout
    );
}
